### ISSUE TITLE
[Slowmist Audit - N6] [Medium] Balance precision loss due to covert U256 to u128

### ISSUE THREAD

**Issue by clostao** [stabilityprotocol/stability#141]
**Note: This issue was one of the elements claimed as a bug during the SlowMist Audit Report. This is a public response for this issue**

### The issue

If actual_balance large than u128::MAX , total_balance function will return u128::MAX , it is an incorrect

```rust
fn total_balance(who: &T::AccountId) -> Self::Balance {
    let evm_address = T::AccountIdMapping::into_evm_address(who);
    let actual_balance =
    <T::UserFeeTokenController as
    UserFeeTokenController>::balance_of(evm_address);
    let maximum_balance = sp_core::U256::from(u128::MAX);
    if maximum_balance < actual_balance {
    u128::MAX //SlowMist//
  } else {
    actual_balance.as_u128()
  }
}
```

### Response

This is a known limitation. Since we have to maintain the Substrate's balance interfaces because they are required by `pallet_evm::Config`, this interfaces are restricted to u128 type instead of the U256 type of ERC20's balance. 

No big consequences can derive from this limitation. This limitation will only make fail transactions in `pallet_ethereum` predispatch checks but we have implemented some fallback checks that will check actual balance (U256-typed) and the transaction would go through then.

**Comment by deblanco** [comment]
For our blockchain, which operates without a native token, we are employing the `pallet_balances` module to represent an ERC20 token. This setup includes specific restrictions on operations such as `send` and `transfer` for smart contracts.
